In [178]:
import numpy as np

from fuzzlab.core.fuzzarray import fuzzarray
from fuzzlab.core.fuzznums import Fuzznum
from fuzzlab.core.ops import get_operation_registry
from fuzzlab.modules.qrofs.op import register_qrofn_operations
register_qrofn_operations()
operation_registry = get_operation_registry()

In [179]:
f1 = Fuzznum('qrofn', 3).create(md = 0.7, nmd=0.4)
f2 = Fuzznum('qrofn', 3).create(md = 0.5, nmd=0.7)

fy1 = [[Fuzznum('qrofn', qrung=3).create(md=0.7, nmd=0.4),
        Fuzznum('qrofn', qrung=3).create(md=0.5, nmd=0.6),
        Fuzznum('qrofn', qrung=3).create(md=0.8, nmd=0.3)],
       [Fuzznum('qrofn', qrung=3).create(md=0.4, nmd=0.2),
        Fuzznum('qrofn', qrung=3).create(md=0.5, nmd=0.7),
        Fuzznum('qrofn', qrung=3).create(md=0.5, nmd=0.1)],
       [Fuzznum('qrofn', qrung=3).create(md=0.8, nmd=0.6),
        Fuzznum('qrofn', qrung=3).create(md=0.2, nmd=0.3),
        Fuzznum('qrofn', qrung=3).create(md=0.6, nmd=0.3)]]

fy2 = [[Fuzznum('qrofn', qrung=3).create(md=0.2, nmd=0.8),
        Fuzznum('qrofn', qrung=3).create(md=0.8, nmd=0.5),
        Fuzznum('qrofn', qrung=3).create(md=0.3, nmd=0.5)],
       [Fuzznum('qrofn', qrung=3).create(md=0.4, nmd=0.4),
        Fuzznum('qrofn', qrung=3).create(md=0.1, nmd=0.7),
        Fuzznum('qrofn', qrung=3).create(md=0.9, nmd=0.3)],
       [Fuzznum('qrofn', qrung=3).create(md=0.3, nmd=0.3),
        Fuzznum('qrofn', qrung=3).create(md=0.4, nmd=0.7),
        Fuzznum('qrofn', qrung=3).create(md=0.6, nmd=0.2)]]
s1 = fuzzarray(fy1)
s2 = fuzzarray(fy2)

n = np.random.rand(3,3)

### addition
1. Fuzznum + Fuzznum
2. Fuzznum + Fuzzarray
3. Fuzzarray + Fuzznum
4. Fuzzarray + Fuzzarray

In [180]:
f1 + f2

<0.751921,0.28>

In [181]:
f1 + s1

Fuzzarray([[<0.828334,0.16> <0.751921,0.24> <0.8791,0.12>]
           [<0.727509,0.08> <0.751921,0.28> <0.751921,0.04>]
           [<0.8791,0.24> <0.703557,0.12> <0.785635,0.12>]], qrung=3, mtype=qrofn)

In [182]:
s2 + f2

Fuzzarray([[<0.509164,0.56> <0.830587,0.35> <0.529701,0.35>]
           [<0.565665,0.28> <0.501164,0.49> <0.91373,0.21>]
           [<0.529701,0.21> <0.565665,0.49> <0.679688,0.14>]], qrung=3, mtype=qrofn)

In [183]:
s1 + s2

Fuzzarray([[<0.703557,0.32> <0.830587,0.3> <0.806804,0.15>]
           [<0.498534,0.08> <0.501164,0.49> <0.91373,0.03>]
           [<0.806804,0.18> <0.415028,0.21> <0.727695,0.06>]], qrung=3, mtype=qrofn)

### subtraction
1. Fuzznum + Fuzznum
2. Fuzznum + Fuzzarray
3. Fuzzarray + Fuzznum
4. Fuzzarray + Fuzzarray

In [184]:
f1 - f2

<0.62924,0.571429>

In [185]:
f1 - s1

Fuzzarray([[<0.0,1.0> <0.62924,0.666667> <0.0,1.0>]
           [<0.0,1.0> <0.62924,0.571429> <0.0,1.0>]
           [<0.0,1.0> <0.0,1.0> <0.0,1.0>]], qrung=3, mtype=qrofn)

In [186]:
s2 - f2

Fuzzarray([[<0.0,1.0> <0.761905,0.714286> <0.0,1.0>]
           [<0.0,1.0> <0.0,1.0> <0.883778,0.428571>]
           [<0.0,1.0> <0.0,1.0> <0.470267,0.285714>]], qrung=3, mtype=qrofn)

In [187]:
s1 - s2

Fuzzarray([[<0.696377,0.5> <0.0,1.0> <0.792884,0.6>]
           [<0.0,1.0> <0.0,1.0> <0.0,1.0>]
           [<0.0,1.0> <0.0,1.0> <0.0,1.0>]], qrung=3, mtype=qrofn)

### Multiplication

---
1. Fuzznum * Fuzznum
2. Fuzznum * int | float
3. Fuzznum * ndarray
4. Fuzznum * Fuzzarray
---
5. Fuzzarray * Fuzznum
6. Fuzzarray * int | float
7. Fuzzarray * ndarray
8. Fuzzarray * Fuzzarray
---
9. int | float * Fuzznum
10. int | float * Fuzzarray
11. ndarray * Fuzznum
12. ndarray * Fuzzarray

In [188]:
f1 * f2

<0.35,0.727509>

In [189]:
f1 * 0.5

<0.574329,0.632456>

In [190]:
f1 * n

Fuzzarray([[<0.65554,0.485908> <0.673953,0.450609> <0.60687,0.57592>]
           [<0.530258,0.703156> <0.408719,0.85705> <0.699484,0.401007>]
           [<0.368538,0.894035> <0.601152,0.586094> <0.493041,0.756937>]], qrung=3, mtype=qrofn)

In [191]:
f1 * s1

Fuzzarray([[<0.49,0.498534> <0.35,0.643265> <0.56,0.446929>]
           [<0.28,0.415028> <0.35,0.727509> <0.35,0.401941>]
           [<0.56,0.643265> <0.14,0.446929> <0.42,0.446929>]], qrung=3, mtype=qrofn)

In [192]:
s1 * f1

Fuzzarray([[<0.49,0.498534> <0.35,0.643265> <0.56,0.446929>]
           [<0.28,0.415028> <0.35,0.727509> <0.35,0.401941>]
           [<0.56,0.643265> <0.14,0.446929> <0.42,0.446929>]], qrung=3, mtype=qrofn)

In [193]:
s1 * 0.5

Fuzzarray([[<0.574329,0.632456> <0.401216,0.774597> <0.670495,0.547723>]
           [<0.31922,0.447214> <0.401216,0.83666> <0.401216,0.316228>]
           [<0.670495,0.774597> <0.158846,0.547723> <0.485677,0.547723>]], qrung=3, mtype=qrofn)

In [194]:
s1 * n

Fuzzarray([[<0.65554,0.485908> <0.478671,0.641203> <0.705277,0.484312>]
           [<0.292793,0.538705> <0.281174,0.941721> <0.499572,0.100634>]
           [<0.437894,0.939465> <0.167179,0.495584> <0.414641,0.693568>]], qrung=3, mtype=qrofn)

In [195]:
s1 * s2

Fuzzarray([[<0.14,0.815947> <0.4,0.679688> <0.24,0.529701>]
           [<0.16,0.415028> <0.05,0.828334> <0.45,0.303561>]
           [<0.24,0.618992> <0.08,0.711865> <0.36,0.326432>]], qrung=3, mtype=qrofn)

In [196]:
0.5 * f1

<0.574329,0.632456>

In [197]:
0.5 * s1

Fuzzarray([[<0.574329,0.632456> <0.401216,0.774597> <0.670495,0.547723>]
           [<0.31922,0.447214> <0.401216,0.83666> <0.401216,0.316228>]
           [<0.670495,0.774597> <0.158846,0.547723> <0.485677,0.547723>]], qrung=3, mtype=qrofn)

In [198]:
n * f1

Fuzzarray([[<0.65554,0.485908> <0.673953,0.450609> <0.60687,0.57592>]
           [<0.530258,0.703156> <0.408719,0.85705> <0.699484,0.401007>]
           [<0.368538,0.894035> <0.601152,0.586094> <0.493041,0.756937>]], qrung=3, mtype=qrofn)

In [199]:
n * s1

Fuzzarray([[<0.65554,0.485908> <0.478671,0.641203> <0.705277,0.484312>]
           [<0.292793,0.538705> <0.281174,0.941721> <0.499572,0.100634>]
           [<0.437894,0.939465> <0.167179,0.495584> <0.414641,0.693568>]], qrung=3, mtype=qrofn)

### Division
1. Fuzznum / Fuzznum
2. Fuzznum / Fuzzarray
3. Fuzznum / int | float
4. Fuzznum / ndarray
---
5. Fuzzarray / Fuzznum
6. Fuzzarray / Fuzzarray
7. Fuzzarray / int | float
8. Fuzzarray / ndarray

In [200]:
f1 / f2

<1.0,0.0>

In [201]:
f1 / s1

Fuzzarray([[<1.0,0.0> <1.0,0.0> <0.875,0.336276>]
           [<1.0,0.0> <1.0,0.0> <1.0,0.0>]
           [<1.0,0.0> <1.0,0.0> <1.0,0.0>]], qrung=3, mtype=qrofn)

In [202]:
f1 / 2

<0.574329,0.632456>

In [203]:
f1 / n

Fuzzarray([[<0.744907,0.312456> <0.726203,0.348809> <0.794865,0.218366>]
           [<0.872751,0.092181> <0.971714,0.004328> <0.700516,0.398992>]
           [<0.989156,0.000556> <0.800758,0.207743> <0.908146,0.049048>]], qrung=3, mtype=qrofn)

In [204]:
s1 / f1

Fuzzarray([[<1.0,0.0> <0.714286,0.545577> <1.0,0.0>]
           [<1.0,0.0> <0.714286,0.667999> <1.0,0.0>]
           [<1.0,0.0> <1.0,0.0> <1.0,0.0>]], qrung=3, mtype=qrofn)

In [205]:
s1 / s2

Fuzzarray([[<1.0,0.0> <0.625,0.470267> <1.0,0.0>]
           [<1.0,0.0> <1.0,0.0> <1.0,0.0>]
           [<1.0,0.0> <1.0,0.0> <1.0,0.0>]], qrung=3, mtype=qrofn)

In [206]:
s1 / 2

Fuzzarray([[<0.574329,0.632456> <0.401216,0.774597> <0.670495,0.547723>]
           [<0.31922,0.447214> <0.401216,0.83666> <0.401216,0.316228>]
           [<0.670495,0.774597> <0.158846,0.547723> <0.485677,0.547723>]], qrung=3, mtype=qrofn)

In [207]:
s1 / n

Fuzzarray([[<0.744907,0.312456> <0.522064,0.555899> <0.886293,0.135429>]
           [<0.540715,0.015185> <0.818124,0.120196> <0.500428,0.099368>]
           [<0.999057,0.015317> <0.239169,0.126839> <0.819811,0.019034>]], qrung=3, mtype=qrofn)

### power
1. Fuzznum ^ int | float
2. Fuzznum ^ ndarray
3. Fuzzarray ^ int | float
4. Fuzzarray ^ ndarray

In [208]:
f1 ** 2

<0.828334,0.16>

In [209]:
f1 ** n

Fuzzarray([[<0.65554,0.485908> <0.673953,0.450609> <0.60687,0.57592>]
           [<0.530258,0.703156> <0.408719,0.85705> <0.699484,0.401007>]
           [<0.368538,0.894035> <0.601152,0.586094> <0.493041,0.756937>]], qrung=3, mtype=qrofn)

In [210]:
s1 ** 2

Fuzzarray([[<0.828334,0.16> <0.616553,0.36> <0.913323,0.09>]
           [<0.498534,0.04> <0.616553,0.49> <0.616553,0.01>]
           [<0.913323,0.36> <0.251648,0.09> <0.727695,0.09>]], qrung=3, mtype=qrofn)

In [211]:
s1 ** n

Fuzzarray([[<0.65554,0.485908> <0.478671,0.641203> <0.705277,0.484312>]
           [<0.292793,0.538705> <0.281174,0.941721> <0.499572,0.100634>]
           [<0.437894,0.939465> <0.167179,0.495584> <0.414641,0.693568>]], qrung=3, mtype=qrofn)

### greater
1. Fuzznum > Fuzznum
2. Fuzznum > Fuzzarray
3. Fuzzarray > Fuzznum
4. Fuzzarray > Fuzzarray

In [212]:
f1 > f2

True

In [213]:
f1 > s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [214]:
s2 > f2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [215]:
s2 > s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### lesser
1. Fuzznum < Fuzznum
2. Fuzznum < Fuzzarray
3. Fuzzarray < Fuzznum
4. Fuzzarray < Fuzzarray

In [216]:
f1 < f2

False

In [217]:
f1 < s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [218]:
s1 < f1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [219]:
s1 < s2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### eq
1. Fuzznum == Fuzznum
2. Fuzznum == Fuzzarray
3. Fuzzarray == Fuzznum
4. Fuzzarray == Fuzzarray

In [220]:
f1 == f2

False

In [221]:
f1 == s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [222]:
s1 == f1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [223]:
s1 == s2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### neq
1. Fuzznum != Fuzznum
2. Fuzznum != Fuzzarray
3. Fuzzarray != Fuzznum
4. Fuzzarray != Fuzzarray

In [224]:
f1 != f2

True

In [225]:
f1 != s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [226]:
s1 != f1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [227]:
s1 != s2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### greater and equal
1. Fuzznum >= Fuzznum
2. Fuzznum >= Fuzzarray
3. Fuzzarray >= Fuzznum
4. Fuzzarray >= Fuzzarray

In [228]:
f1 >= f2

True

In [229]:
f1 >= s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [230]:
s1 >= f1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [231]:
s1 >= s2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### lesser and equal
1. Fuzznum <= Fuzznum
2. Fuzznum <= Fuzzarray
3. Fuzzarray <= Fuzznum
4. Fuzzarray <= Fuzzarray


In [232]:
f1 <= f2

False

In [233]:
f1 <= s1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [234]:
s1 <= f1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [235]:
s1 <= s2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [236]:
operation_registry.get_performance_stats()

{'total_operations': 1560,
 'total_time(us)': 11189.914047,
 'average_time_per_total_operation(us)': 7.173022,
 'operation_counts_by_type': {'add': {'binary': 112},
  'sub': {'binary': 112},
  'mul': {'binary': 112},
  'tim': {'unary_operand': 328},
  'div': {'binary': 112},
  'pow': {'unary_operand': 112},
  'gt': {'comparison': 112},
  'lt': {'comparison': 112},
  'eq': {'comparison': 112},
  'ne': {'comparison': 112},
  'ge': {'comparison': 112},
  'le': {'comparison': 112}},
 'average_times_by_operation_type(us)': {'add': {'binary': 15.399579},
  'sub': {'binary': 3.759999},
  'mul': {'binary': 14.773133},
  'tim': {'unary_operand': 12.036807},
  'div': {'binary': 3.260383},
  'pow': {'unary_operand': 13.876525},
  'gt': {'comparison': 3.816973},
  'lt': {'comparison': 1.828499},
  'eq': {'comparison': 1.850056},
  'ne': {'comparison': 1.865704},
  'ge': {'comparison': 2.077376},
  'le': {'comparison': 2.151071}}}